package br.com.ortus.gui;

import br.com.ortus.beans.Componente;
import br.com.ortus.beans.Log;
import br.com.ortus.beans.Usuario;
import br.com.ortus.configuracaoPersistencia.TransactionManager;
import br.com.ortus.daosSistema.ComponenteDao;
import br.com.ortus.daosSistema.LogDao;
import br.com.ortus.utilidades.HashSistema;
import br.com.ortus.utilidades.ReportManage;
import br.com.ortus.utilidades.Utilidades;
import java.awt.Color;
import java.awt.Component;
import java.net.InetAddress;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author TI
 */
public class JDialogTabelaDePreco extends javax.swing.JDialog {

    /**
     * Creates new form JDialogTabelaDePreco
     */
    List<Componente> componentes;
    String filtro = "";

    public JDialogTabelaDePreco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popularTabela();
        pintarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePecas = new javax.swing.JTable();
        jTextFieldResultado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxFiltro = new javax.swing.JComboBox();
        jTextFieldFiltro = new javax.swing.JTextField();
        jButtonPesquisa = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jComboBoxTipoOperacao = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldValorCusto = new javax.swing.JTextField();
        jButtonAlterarCusto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldValorCliente = new javax.swing.JTextField();
        jButtonAlterarValorCliente = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldValorTecnico = new javax.swing.JTextField();
        jButtonAlterarValorTecnico = new javax.swing.JButton();
        jComboBoxRelacaoCusto = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldValorRelacao = new javax.swing.JTextField();
        jButtonAlterarValorRelacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Atualização de Tabela de Preços");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTablePecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePecas.setEditingColumn(0);
        jTablePecas.setEditingRow(0);
        jScrollPane1.setViewportView(jTablePecas);

        jLabel2.setText("Resultado(s).");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/close.png"))); // NOI18N
        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/der.png"))); // NOI18N
        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/save.png"))); // NOI18N
        jButton3.setText("Salvar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisa"));

        jComboBoxFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nome", "Valor", "ID" }));

        jTextFieldFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFiltroKeyPressed(evt);
            }
        });

        jButtonPesquisa.setText("Pesquisar");
        jButtonPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisa))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Operações"));

        jComboBoxTipoOperacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "%", "+", "-" }));

        jLabel3.setText("Custo");

        jButtonAlterarCusto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/reloadpequeno.png"))); // NOI18N
        jButtonAlterarCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarCustoActionPerformed(evt);
            }
        });

        jLabel4.setText("Cliente");

        jButtonAlterarValorCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/reloadpequeno.png"))); // NOI18N
        jButtonAlterarValorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarValorClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Técnico");

        jButtonAlterarValorTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/reloadpequeno.png"))); // NOI18N
        jButtonAlterarValorTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarValorTecnicoActionPerformed(evt);
            }
        });

        jComboBoxRelacaoCusto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "% Custo -> Tecnico", "+  Custo -> Tecnico", "% Custo -> Cliente Final", "+ Custo -> Cliente Final" }));

        jLabel6.setText("Alterar valores em relaçao");

        jButtonAlterarValorRelacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/reloadpequeno.png"))); // NOI18N
        jButtonAlterarValorRelacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarValorRelacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxTipoOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextFieldValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarCusto))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextFieldValorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarValorCliente))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextFieldValorTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAlterarValorTecnico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jComboBoxRelacaoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValorRelacao, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAlterarValorRelacao)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxTipoOperacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterarValorRelacao, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValorRelacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxRelacaoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldValorCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAlterarCusto))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldValorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAlterarValorCliente))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldValorTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonAlterarValorTecnico))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        imprimirRelatorio();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAlterarCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarCustoActionPerformed
        // TODO add your handling code here:
        alterarValorAoCusto();
    }//GEN-LAST:event_jButtonAlterarCustoActionPerformed

    private void jButtonAlterarValorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarValorClienteActionPerformed
        // TODO add your handling code here:
        alterarValorCliente();
    }//GEN-LAST:event_jButtonAlterarValorClienteActionPerformed

    private void jButtonAlterarValorTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarValorTecnicoActionPerformed
        // TODO add your handling code here:
        alterarValorTecnico();
    }//GEN-LAST:event_jButtonAlterarValorTecnicoActionPerformed

    private void jTextFieldFiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFiltroKeyPressed
        // TODO add your handling code here:
        pesquisar();
    }//GEN-LAST:event_jTextFieldFiltroKeyPressed

    private void jButtonPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaActionPerformed
        // TODO add your handling code here:
        pesquisar();
    }//GEN-LAST:event_jButtonPesquisaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        salvarAlteracoes();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButtonAlterarValorRelacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarValorRelacaoActionPerformed
        // TODO add your handling code here:
        alterarValorEmRelacaoAoCusto();
    }//GEN-LAST:event_jButtonAlterarValorRelacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogTabelaDePreco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogTabelaDePreco dialog = new JDialogTabelaDePreco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAlterarCusto;
    private javax.swing.JButton jButtonAlterarValorCliente;
    private javax.swing.JButton jButtonAlterarValorRelacao;
    private javax.swing.JButton jButtonAlterarValorTecnico;
    private javax.swing.JButton jButtonPesquisa;
    private javax.swing.JComboBox jComboBoxFiltro;
    private javax.swing.JComboBox jComboBoxRelacaoCusto;
    private javax.swing.JComboBox jComboBoxTipoOperacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePecas;
    private javax.swing.JTextField jTextFieldFiltro;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldValorCliente;
    private javax.swing.JTextField jTextFieldValorCusto;
    private javax.swing.JTextField jTextFieldValorRelacao;
    private javax.swing.JTextField jTextFieldValorTecnico;
    // End of variables declaration//GEN-END:variables

    private void imprimirRelatorio() {
        final Progress p = new Progress();
        p.setVisible(true);
        p.setAlwaysOnTop(true);
        final SwingWorker worker = new SwingWorker() {
            @Override
            protected Object doInBackground() throws Exception {
                buscarDadosRelatorio();
                return null;
            }

            @Override
            protected void done() {
                p.setVisible(false);
            }
        };
        worker.execute();
    }

    private void buscarDadosRelatorio() {
        ReportManage report = new ReportManage();

        try {
            report.relatorioPronto("pecas", "Preço de Peças");


        } catch (JRException ex) {
            Logger.getLogger(JDialogExpedicao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(JDialogExpedicao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popularTabela() {
        ComponenteDao cDao = new ComponenteDao();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "Código", "Componente", "U.M.", "Valor de Custo", "Valor Cliente Final R$", "Valor Técnico R$"});

        componentes = cDao.obterLista(filtro);

        if (componentes != null) {
            for (Componente comp : componentes) {
                model.addRow(new Object[]{comp.getIdProdusys(), comp.getNome(), comp.getUnidadeMedida(), new Utilidades().formatarValorDoubleParaString(comp.getCusto()), new Utilidades().formatarValorDoubleParaString(comp.getValor()), new Utilidades().formatarValorDoubleParaString(comp.getQtde())});
            }
            jTablePecas.setModel(model);
            definirTamanhoDasColunas(jTablePecas);
        }
        jTextFieldResultado.setText(String.valueOf(componentes.size()));
    }

    private void popularTabelaModificada() {
        ComponenteDao cDao = new ComponenteDao();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{
            "Codigo", "Componente", "U.M.", "Valor de Custo", "Valor Cliente Final R$", "Valor Técnico R$"});
        if (componentes == null) {
            componentes = cDao.obterLista(filtro);
        }

        if (componentes != null) {
            for (Componente comp : componentes) {
                model.addRow(new Object[]{comp.getIdProdusys(), comp.getNome(), comp.getUnidadeMedida(), new Utilidades().formatarValorDoubleParaString(comp.getCusto()), new Utilidades().formatarValorDoubleParaString(comp.getValor()), new Utilidades().formatarValorDoubleParaString(comp.getQtde())});
            }
            jTablePecas.setModel(model);
            definirTamanhoDasColunas(jTablePecas);
        }
        jTextFieldResultado.setText(String.valueOf(componentes.size()));
    }

    private void pintarTabela() {
        jTablePecas.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected,
                        hasFocus, row, column);
                if (row % 2 == 0) {
                    setBackground(new Color(204, 255, 204));
                    setForeground(Color.BLACK);
                } else if (row % 2 == 1) {
                    setBackground(new Color(232, 255, 232));
                    setForeground(Color.BLACK);
                }
                return this;
            }
        });
    }

    private void definirTamanhoDasColunas(JTable tabela) {
        tabela.getColumnModel().getColumn(0).setPreferredWidth(30);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(280);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(10);
    }

    private void alterarValorAoCusto() {
        if (verificarSeEntradaENumero(jTextFieldValorCusto.getText())) {
            double convertido = Double.parseDouble(jTextFieldValorCusto.getText());
            if (jComboBoxTipoOperacao.getSelectedIndex() == 0) {
                for (int i = 0; i < componentes.size(); i++) {
                    double valorAntigo = componentes.get(i).getCusto();
                    double valorNovo = valorAntigo + (valorAntigo * (convertido / 100.0));
                    componentes.get(i).setCusto(valorNovo);
                }
                popularTabelaModificada();
            }
            if (jComboBoxTipoOperacao.getSelectedIndex() == 1) {
                for (int i = 0; i < componentes.size(); i++) {
                    double valorAntigo = componentes.get(i).getCusto();
                    double valorNovo = valorAntigo + convertido;
                    componentes.get(i).setCusto(valorNovo);
                }
                popularTabelaModificada();
            }
            if (jComboBoxTipoOperacao.getSelectedIndex() == 2) {
                for (int i = 0; i < componentes.size(); i++) {
                    double valorAntigo = componentes.get(i).getCusto();
                    double valorNovo = valorAntigo - convertido;
                    componentes.get(i).setCusto(valorNovo);
                }
                popularTabelaModificada();
            }
        }
    }

    private boolean verificarSeEntradaENumero(String valor) {
        try {
            double convertido = Double.parseDouble(valor);
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Digite um número!");
            return false;
        }
    }

    private void alterarValorCliente() {
        if (verificarSeEntradaENumero(jTextFieldValorCliente.getText())) {
            double convertido = Double.parseDouble(jTextFieldValorCliente.getText());
            if (jComboBoxTipoOperacao.getSelectedIndex() == 0) {
                for (int i = 0; i < componentes.size(); i++) {
                    double valorAntigo = componentes.get(i).getValor();
                    double valorNovo = valorAntigo + (valorAntigo * (convertido / 100.0));
                    componentes.get(i).setValor(valorNovo);
                }
                popularTabelaModificada();
            }
            if (jComboBoxTipoOperacao.getSelectedIndex() == 1) {
                for (int i = 0; i < componentes.size(); i++) {
                    double valorAntigo = componentes.get(i).getValor();
                    double valorNovo = valorAntigo + convertido;
                    componentes.get(i).setValor(valorNovo);
                }
                popularTabelaModificada();
            }
            if (jComboBoxTipoOperacao.getSelectedIndex() == 2) {
                for (int i = 0; i < componentes.size(); i++) {
                    double valorAntigo = componentes.get(i).getValor();
                    double valorNovo = valorAntigo - convertido;
                    componentes.get(i).setValor(valorNovo);
                }
                popularTabelaModificada();
            }
        }
    }

    private void alterarValorTecnico() {
        if (verificarSeEntradaENumero(jTextFieldValorTecnico.getText())) {
            double convertido = Double.parseDouble(jTextFieldValorTecnico.getText());
            if (jComboBoxTipoOperacao.getSelectedIndex() == 0) {
                for (int i = 0; i < componentes.size(); i++) {
                    double valorAntigo = componentes.get(i).getQtde();
                    double valorNovo = valorAntigo + (valorAntigo * (convertido / 100.0));
                    componentes.get(i).setQtde(valorNovo);
                }
                popularTabelaModificada();
            }
            if (jComboBoxTipoOperacao.getSelectedIndex() == 1) {
                for (int i = 0; i < componentes.size(); i++) {
                    double valorAntigo = componentes.get(i).getQtde();
                    double valorNovo = valorAntigo + convertido;
                    componentes.get(i).setQtde(valorNovo);
                }
                popularTabelaModificada();
            }
            if (jComboBoxTipoOperacao.getSelectedIndex() == 2) {
                for (int i = 0; i < componentes.size(); i++) {
                    double valorAntigo = componentes.get(i).getQtde();
                    double valorNovo = valorAntigo - convertido;
                    componentes.get(i).setQtde(valorNovo);
                }
                popularTabelaModificada();
            }
        }
    }

    private void pesquisar() {
        if (jTextFieldFiltro.getText().isEmpty()) {
            filtro = "";
            popularTabela();
        } else {
            if (jComboBoxFiltro.getSelectedIndex() == 0) {
                pesquisarPorNome();
                filtro = "";
            } else if (jComboBoxFiltro.getSelectedIndex() == 1) {
                if (verSeENumero()) {
                    pesquisarPorValor();
                    filtro = "";
                }
            } else if (jComboBoxFiltro.getSelectedIndex() == 2) {
                if (verSeENumero()) {
                    pesquisarPorID();
                    filtro = "";
                }
            }
        }
    }

    private void pesquisarPorNome() {
        filtro = "nome LIKE '%" + jTextFieldFiltro.getText() + "%'";
        popularTabela();
    }

    private boolean verSeENumero() {
        try {
            int valor = Integer.parseInt(jTextFieldFiltro.getText());
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Valor incorreto, informe um numero!!!");
            return false;
        }
    }

    private void pesquisarPorValor() {
        filtro = "valor LIKE '%" + jTextFieldFiltro.getText() + "%'";
        popularTabela();
    }

    private void pesquisarPorID() {
        filtro = "idProdusys LIKE '%" + jTextFieldFiltro.getText() + "%'";
        popularTabela();
    }

    private void salvarAlteracoes() {
        try {
            TransactionManager.beginTransaction();
            ComponenteDao dao = new ComponenteDao();
            for (int i = 0; i < componentes.size(); i++) {
                dao.persistir(componentes.get(i));
            }
            Usuario user = (Usuario) HashSistema.hash.get("usuarioLogado");
            String ip = pegarIPDaMaquina();
            new LogDao().persistir(new Log(user, Utilidades.retData(), "Desktop", "***Tabela de Preços***", ip));

            TransactionManager.commit();
            JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar: " + e);
            TransactionManager.rollback();
        }
    }

    private void alterarValorEmRelacaoAoCusto() {
        if (verificarSeEntradaENumero(jTextFieldValorRelacao.getText())) {
            double valorEntrada = Double.parseDouble(jTextFieldValorRelacao.getText());
            if (jComboBoxRelacaoCusto.getSelectedIndex() == 0) {
                //Alterar valor para o tecnico em relação ao Custo em porcentagem              
                for (int i = 0; i < componentes.size(); i++) {
                    double novoValor = 0.0;
                    double valorCusto = componentes.get(i).getCusto();
                    novoValor = valorCusto + (valorCusto * (valorEntrada / 100));
                    componentes.get(i).setQtde(novoValor);
                    /*Estou usando a variavel Qtde em Componente pois alterei a função para guardar o valor pago pelo técnico
                     e daria muito trabalho trocar o nome da variável em todas as classes e relatórios =}*/
                }
            }
            if (jComboBoxRelacaoCusto.getSelectedIndex() == 1) {
                //Alterar valor para o tecnico em relação ao Custo em Somatório               
                for (int i = 0; i < componentes.size(); i++) {
                    double novoValor = 0.0;
                    double valorCusto = componentes.get(i).getCusto();
                    novoValor = valorCusto + valorEntrada;
                    componentes.get(i).setQtde(novoValor);
                    /*Estou usando a variavel Qtde em Componente pois alterei a função para guardar o valor pago pelo técnico
                     e daria muito trabalho trocar o nome da variável em todas as classes e relatórios =}*/
                }
            }
            if (jComboBoxRelacaoCusto.getSelectedIndex() == 2) {
                //Alterar valor para o Cliente Final em relação ao Custo em porcentagem             
                for (int i = 0; i < componentes.size(); i++) {
                    double novoValor = 0.0;
                    double valorCusto = componentes.get(i).getCusto();
                    novoValor = valorCusto + (valorCusto * (valorEntrada / 100));
                    componentes.get(i).setValor(novoValor);
                }
            }
            if (jComboBoxRelacaoCusto.getSelectedIndex() == 3) {
                //Alterar valor para o Cliente Final em relação ao Custo em Somatório.               
                for (int i = 0; i < componentes.size(); i++) {
                    double novoValor = 0.0;
                    double valorCusto = componentes.get(i).getCusto();
                    novoValor = valorCusto + valorEntrada;
                    componentes.get(i).setValor(novoValor);
                }
            }
            popularTabelaModificada();
        }
    }

    private String pegarIPDaMaquina() {
        try {
            return InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (Exception e) {
            System.out.println(e);
            return " . . . ";
        }
    }
}
