/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ortus.gui;

import br.com.ortus.beans.*;
import br.com.ortus.configuracaoPersistencia.TransactionManager;
import br.com.ortus.daosSistema.LogDao;
import br.com.ortus.daosSistema.RegistroAutoclaveDao;
import br.com.ortus.utilidades.HashSistema;
import br.com.ortus.utilidades.Utilidades;
import java.awt.Color;
import java.awt.Component;
import java.net.InetAddress;
import java.util.Collections;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ti
 */
public class JDialogRegistrosAutoclave extends javax.swing.JDialog {

    /**
     * Creates new form JDialogRegistrosAutoclave
     */
    private Cliente revenda;
    private Cliente clienteFinal;
    private Autoclave autoclave;
    private List<RegistroAutoclave> registrosBloqueados;
    private List<RegistroAutoclave> registrosDesbloqueados;

    public JDialogRegistrosAutoclave(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarTabelaRegistrosBloqueados();
        carregarTabelaRegistrosDesbloqueados();
        pintarTabelaBloqueados();
        pintarTabelaDesbloqueados();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton = new javax.swing.JPanel();
        jTextFieldCodigoRegistro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodigoRevenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonPesquisaRevenda = new javax.swing.JButton();
        jTextFieldNomeRevenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodigoCliente = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jFormattedTextFieldDataRegistro = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextFieldDataDesbloqueio = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldCodigoProduto = new javax.swing.JTextField();
        jButtonPesquisaProduto = new javax.swing.JButton();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jTextFieldNumeroSerie = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCodigoDesbloqueio = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBloqueados = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDesbloqueados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Controle de registros Autoclave");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(334, 334, 334))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro"));

        jTextFieldCodigoRegistro.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldCodigoRegistro.setEditable(false);

        jLabel2.setText("Cod");

        jTextFieldCodigoRevenda.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldCodigoRevenda.setEditable(false);

        jLabel3.setText("Cod. Revenda");

        jButtonPesquisaRevenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/pesquisarpequeno.png"))); // NOI18N
        jButtonPesquisaRevenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaRevendaActionPerformed(evt);
            }
        });

        jTextFieldNomeRevenda.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldNomeRevenda.setEditable(false);

        jLabel4.setText("Cod. Cliente");

        jTextFieldCodigoCliente.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldCodigoCliente.setEditable(false);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/pesquisarpequeno.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldNomeCliente.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldNomeCliente.setEditable(false);

        try {
            jFormattedTextFieldDataRegistro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Data Registro");

        jLabel6.setText("Data Desbloqueio");

        try {
            jFormattedTextFieldDataDesbloqueio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("Cod. Produto:");

        jTextFieldCodigoProduto.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldCodigoProduto.setEditable(false);

        jButtonPesquisaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/pesquisarpequeno.png"))); // NOI18N
        jButtonPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaProdutoActionPerformed(evt);
            }
        });

        jTextFieldNomeProduto.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldNomeProduto.setEditable(false);

        jTextFieldNumeroSerie.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldNumeroSerie.setEditable(false);

        jLabel8.setText("Produto");

        jLabel9.setText("Numero de série");

        jLabel10.setText("Código de desbloqueio");

        jTextFieldCodigoDesbloqueio.setBackground(new java.awt.Color(204, 255, 204));
        jTextFieldCodigoDesbloqueio.setEditable(false);

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/save.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/limpar.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ortus/icones/close.png"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel11.setText("Nome Revenda");

        jLabel12.setText("Nome Cliente");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bloqueado", "Desbloqueado" }));

        jLabel13.setText("Status");

        javax.swing.GroupLayout jButtonLayout = new javax.swing.GroupLayout(jButton);
        jButton.setLayout(jButtonLayout);
        jButtonLayout.setHorizontalGroup(
            jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCodigoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jButtonLayout.createSequentialGroup()
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextFieldDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCodigoRevenda, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisaRevenda, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomeRevenda, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonLayout.createSequentialGroup()
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jFormattedTextFieldDataDesbloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jButtonLayout.createSequentialGroup()
                                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jButtonLayout.createSequentialGroup()
                                .addComponent(jButtonSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonFechar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jButtonLayout.createSequentialGroup()
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNomeCliente)
                            .addGroup(jButtonLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jButtonLayout.createSequentialGroup()
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigoDesbloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jButtonLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jComboBoxStatus, 0, 129, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jButtonLayout.setVerticalGroup(
            jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonLayout.createSequentialGroup()
                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jButtonLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jButtonLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jButtonLayout.createSequentialGroup()
                            .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldCodigoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFormattedTextFieldDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(1, 1, 1)))
                    .addGroup(jButtonLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodigoRevenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisaRevenda, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jButtonLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldNomeRevenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jButtonLayout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextFieldDataDesbloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jButtonLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jButtonLayout.createSequentialGroup()
                                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jButtonLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)))
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCodigoDesbloqueio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonFechar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableBloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableBloqueados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBloqueadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableBloqueados);

        jTabbedPane1.addTab("Bloqueados", jScrollPane1);

        jTableDesbloqueados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableDesbloqueados);

        jTabbedPane1.addTab("Desbloqueados", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisaRevendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaRevendaActionPerformed
        // TODO add your handling code here:
        buscarRevenda();
    }//GEN-LAST:event_jButtonPesquisaRevendaActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        salvarRegistro();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        limparFormulario();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaProdutoActionPerformed
        // TODO add your handling code here:
        buscarAutoclave();
    }//GEN-LAST:event_jButtonPesquisaProdutoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        buscarClienteFinal();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTableBloqueadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBloqueadosMouseClicked
        // TODO add your handling code here:
        editarLinhaRegistro();
    }//GEN-LAST:event_jTableBloqueadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogRegistrosAutoclave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogRegistrosAutoclave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogRegistrosAutoclave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogRegistrosAutoclave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JDialogRegistrosAutoclave dialog = new JDialogRegistrosAutoclave(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisaProduto;
    private javax.swing.JButton jButtonPesquisaRevenda;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxStatus;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataDesbloqueio;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBloqueados;
    private javax.swing.JTable jTableDesbloqueados;
    private javax.swing.JTextField jTextFieldCodigoCliente;
    private javax.swing.JTextField jTextFieldCodigoDesbloqueio;
    private javax.swing.JTextField jTextFieldCodigoProduto;
    private javax.swing.JTextField jTextFieldCodigoRegistro;
    private javax.swing.JTextField jTextFieldCodigoRevenda;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldNomeRevenda;
    private javax.swing.JTextField jTextFieldNumeroSerie;
    // End of variables declaration//GEN-END:variables

    private void salvarRegistro() {
        if (!validarCampos()) {
            return;
        }
        int opcao = JOptionPane.showConfirmDialog(rootPane,
                "Deseja salvar?", "Confirmação",
                JOptionPane.YES_NO_OPTION);
        if (opcao != JOptionPane.YES_OPTION) {
            return;
        }
        RegistroAutoclave registro = new RegistroAutoclave();

        if (!jTextFieldCodigoRegistro.getText().isEmpty()) {
            autoclave.setId(Integer.parseInt(jTextFieldCodigoRegistro.getText()));
        }
        registro.setDataRegistro(jFormattedTextFieldDataRegistro.getText());
        registro.setDataDesbloqueio(jFormattedTextFieldDataDesbloqueio.getText());

        registro.setRevenda(revenda);
        registro.setClienteFinal(clienteFinal);

        registro.setAutoclave(autoclave);

        registro.setStatus(jComboBoxStatus.getSelectedItem().toString());

        Usuario user = (Usuario) HashSistema.hash.get("usuarioLogado");
        String ip = pegarIPDaMaquina();
        Log log = new Log(user, Utilidades.retData(), "Desktop", "Inserto/Update - Registro: " + autoclave.getNumeroSerie(), ip);

        TransactionManager.beginTransaction();
        try {
            RegistroAutoclaveDao tDao = new RegistroAutoclaveDao();
            new LogDao().persistir(log);
            tDao.persistir(registro);

            TransactionManager.commit();

            JOptionPane.showMessageDialog(null, "Registro foi gravado!");
            carregarTabelaRegistrosBloqueados();
            carregarTabelaRegistrosDesbloqueados();
            limparFormulario();
        } catch (Exception e) {
            TransactionManager.rollback();
            JOptionPane.showMessageDialog(null, "Registro não pode ser gravado!" + e);
        }
    }

    private void limparFormulario() {
        jTextFieldCodigoRegistro.setText(null);
        jTextFieldCodigoCliente.setText(null);
        jTextFieldNomeCliente.setText(null);
        jTextFieldCodigoRevenda.setText(null);
        jTextFieldNomeRevenda.setText(null);
        jTextFieldCodigoProduto.setText(null);
        jTextFieldNomeProduto.setText(null);
        jTextFieldNumeroSerie.setText(null);
        jTextFieldCodigoDesbloqueio.setText(null);
        jFormattedTextFieldDataDesbloqueio.setText(null);
        jFormattedTextFieldDataRegistro.setText(null);
        clienteFinal = new Cliente();
        revenda = new Cliente();
        autoclave = new Autoclave();
    }

    private void buscarAutoclave() {
        JDialog jd = new JDialogCadastroAutoclave(null, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        autoclave = (Autoclave) HashSistema.hash.get("autoclave");
        if (autoclave == null) {
            return;
        }
        HashSistema.hash.remove("autoclave");
        preencherFormularioComAutoclave(autoclave);
    }

    private void buscarRevenda() {
        JDialog jd = new JDialogClienteUltimaVersao(null, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        revenda = (Cliente) HashSistema.hash.get("cliente");
        if (revenda == null) {
            return;
        }
        HashSistema.hash.remove("cliente");
        preencherFormularioComARevenda(revenda);
    }

    private void preencherFormularioComARevenda(Cliente revenda) {
        jTextFieldCodigoRevenda.setText(String.valueOf(revenda.getId()));
        jTextFieldNomeRevenda.setText(revenda.getNome());
    }

    private void buscarClienteFinal() {
        JDialog jd = new JDialogClienteUltimaVersao(null, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        clienteFinal = (Cliente) HashSistema.hash.get("cliente");
        if (clienteFinal == null) {
            return;
        }
        HashSistema.hash.remove("cliente");
        preencherFormularioComOCliente(clienteFinal);
    }

    private void preencherFormularioComOCliente(Cliente clienteFinal) {
        jTextFieldCodigoCliente.setText(String.valueOf(clienteFinal.getId()));
        jTextFieldNomeCliente.setText(clienteFinal.getNome());
    }

    private void preencherFormularioComAutoclave(Autoclave autoclave) {
        jTextFieldCodigoProduto.setText(String.valueOf(autoclave.getId()));
        jTextFieldNomeProduto.setText(autoclave.getNomeAutoclave());
        jTextFieldNumeroSerie.setText(autoclave.getNumeroSerie());
        jTextFieldCodigoDesbloqueio.setText(autoclave.getCodigoDesbloqueio());

    }

    private void carregarTabelaRegistrosBloqueados() {
        RegistroAutoclaveDao dGP = new RegistroAutoclaveDao();
        registrosBloqueados = dGP.obterLista("status ='Bloqueado'");
        mostrarRegistros(registrosBloqueados);
    }

    private void mostrarRegistros(List<RegistroAutoclave> registros) {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Cod", "Registro", "Revenda", "Cliente Final", "Autoclave", "Numero de Serie", "Codigo de Desbloqueio", "Data desbloqueio"});


        Collections.reverse(registros);
        if (registros != null) {
            for (RegistroAutoclave registro : registros) {
                String idRegistro = String.valueOf(registro.getId());
                String nomeRevenda = registro.getRevenda().getNome();
                String nomeClienteFinal = buscarNomeClienteFinal(registro);
                model.addRow(new Object[]{idRegistro, registro.getDataRegistro(), nomeRevenda, nomeClienteFinal, registro.getAutoclave().getNomeAutoclave(), registro.getAutoclave().getNumeroSerie(), registro.getAutoclave().getCodigoDesbloqueio(), registro.getDataDesbloqueio()});
            }
            jTableBloqueados.setModel(model);
            definirTamanhoDasColunas(jTableBloqueados);
        }
    }

    private void definirTamanhoDasColunas(JTable jTableBloqueados) {
        jTableBloqueados.getColumnModel().getColumn(0).setPreferredWidth(4);
        jTableBloqueados.getColumnModel().getColumn(1).setPreferredWidth(70);
    }

    private void carregarTabelaRegistrosDesbloqueados() {
        RegistroAutoclaveDao dGP = new RegistroAutoclaveDao();
        registrosDesbloqueados = dGP.obterLista("status ='Desbloqueado'");
        mostrarRegistrosDesbloqueados(registrosDesbloqueados);
    }

    private void mostrarRegistrosDesbloqueados(List<RegistroAutoclave> registrosDesbloqueados) {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Cod", "Registro", "Revenda", "Cliente Final", "Autoclave", "Numero de Serie", "Codigo de Desbloqueio", "Data desbloqueio"});


        Collections.reverse(registrosDesbloqueados);
        if (registrosDesbloqueados != null) {
            for (RegistroAutoclave registro : registrosDesbloqueados) {
                String idRegistro = String.valueOf(registro.getId());
                String nomeRevenda = registro.getRevenda().getNome();
                String nomeClienteFinal = buscarNomeClienteFinal(registro);
                model.addRow(new Object[]{idRegistro, registro.getDataRegistro(), nomeRevenda, nomeClienteFinal, registro.getAutoclave().getNomeAutoclave(), registro.getAutoclave().getNumeroSerie(), registro.getAutoclave().getCodigoDesbloqueio(), registro.getDataDesbloqueio()});
            }
            jTableDesbloqueados.setModel(model);
            definirTamanhoDasColunas(jTableDesbloqueados);
        }
    }

    private boolean validarCampos() {
        int erros = 0;
        if (revenda == null) {
            JOptionPane.showMessageDialog(rootPane, "A revenda deve ser preenchida!");
            erros++;
        }
        if (autoclave == null) {
            JOptionPane.showMessageDialog(rootPane, "A autoclave deve ser preenchida!");
            erros++;
        }
        if (erros != 0) {
            return false;
        }
        return true;
    }

    private String pegarIPDaMaquina() {
        try {
            return InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (Exception e) {
            System.out.println(e);
            return " . . . ";
        }
    }

    private String buscarNomeClienteFinal(RegistroAutoclave registro) {
        if (registro.getClienteFinal() == null) {
            return " ";
        } else {
            return registro.getClienteFinal().getNome();
        }
    }

    private void pintarTabelaBloqueados() {
        jTableBloqueados.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected,
                        hasFocus, row, column);
                if (row % 2 == 0) {
                    setBackground(new Color(255, 156, 118));
                    setForeground(Color.BLACK);
                } else if (row % 2 == 1) {
                    setBackground(new Color(255, 210, 202));
                    setForeground(Color.BLACK);
                }
                return this;
            }
        });
    }

    private void pintarTabelaDesbloqueados() {
        jTableDesbloqueados.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                super.getTableCellRendererComponent(table, value, isSelected,
                        hasFocus, row, column);
                if (row % 2 == 0) {
                    setBackground(new Color(204, 255, 204));
                    setForeground(Color.BLACK);
                } else if (row % 2 == 1) {
                    setBackground(new Color(232, 255, 232));
                    setForeground(Color.BLACK);
                } 
                return this;
            }
        });
    }

    private void editarLinhaRegistro() {
        int linha = jTableBloqueados.getSelectedRow();
        if(linha != -1){
            RegistroAutoclave registro = registrosBloqueados.get(linha);
            preencherFormularioComRegistro(registro);
        }else{
            JOptionPane.showMessageDialog(null, "Selecione uma linha para editar.");
            return;
        }
    }

    private void preencherFormularioComRegistro(RegistroAutoclave registro) {
        jTextFieldCodigoRegistro.setText(String.valueOf(registro.getId()));
        jFormattedTextFieldDataDesbloqueio.setText(registro.getDataDesbloqueio());
        jFormattedTextFieldDataRegistro.setText(registro.getDataRegistro());
        
        if(registro.getRevenda()!=null){
            //asdasdasd
        }
        clienteFinal = new Cliente();
        revenda = new Cliente();
        autoclave = new Autoclave();
    }
}
